import { Inter } from 'next/font/google';
import Head from 'next/head';
import Link from 'next/link';
import React from 'react';

import styles from '../styles/Home.module.css';

const inter = Inter({ subsets: ["latin"] });

export default function Home(): React.JSX.Element {
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="film,film spot" />
      </Head>
      <main className={styles.main}>
        <h1>AT Recommends</h1>
        <hr className={styles.lines} />
        <h2>Popular Films</h2>
        <div className={styles.grid}>
          <Link
            href="/film"
            className={styles.card}
          >
            <h2 className={inter.className}>
              Se7en <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Two detectives, a rookie and a veteran, hunt a serial killer who
              uses the seven deadly sins as his motives.
            </p>
          </Link>

          <Link
            href="/film"
            className={styles.card}
          >
            <h2 className={inter.className}>
              Fight Club <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              An insomniac office worker and a devil-may-care soap maker form an
              underground fight club that evolves into much more.
            </p>
          </Link>

          <Link
            href="/film"
            className={styles.card}
          >
            <h2 className={inter.className}>
              Prisoners <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Keller Dover is facing every parents worst nightmare. His
              six-year-old daughter, Anna, is missing, together with her friend,
              Joy, and as minutes turn to hours, panic sets in. The only lead is
              an RV that had been parked on their street.
            </p>
          </Link>

          <Link
            href="/film"
            className={styles.card}
          >
            <h2 className={inter.className}>
              Gone Girl <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              The husband of a missing woman becomes the chief suspect in her
              disappearance.
            </p>
          </Link>
        </div>
      </main>
    </>
  );
}
